spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowedHeaders: "*"
              allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ecomarket-servicio-eureka-qa:8761/eureka/}
  instance:
    prefer-ip-address: true
    
server:
    port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG
