spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://ecomarket-servicio-eureka-qa:8761/eureka/}
  instance:
    prefer-ip-address: true
    
server:
    port: 7999

logging:
  level:
    org:
      springframework:
        security: DEBUG
